# Netlify Configuration for CareerAI

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Essential build settings only
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  # Ensure Next.js uses standalone mode for better Netlify compatibility
  NEXT_PRIVATE_STANDALONE = "true"

# Enable Next.js Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Function configuration
[functions]
  # Directory containing Netlify Functions
  directory = "netlify/functions"
  # Use esbuild for faster builds
  node_bundler = "esbuild"
  # Include necessary files in function bundles
  included_files = ["node_modules/@google-cloud/**", "lib/**", ".env*", "**/*.json"]

# Edge Functions configuration
[edge_functions]
  directory = "netlify/edge-functions"

# Configure specific Netlify Functions
[[functions]]
  # Background function for resume processing (15 min timeout)
  path = "/.netlify/functions/process-resume-background"
  name = "process-resume-background"

[[functions]]
  # Background function for document generation (15 min timeout)
  path = "/.netlify/functions/generate-documents-background"
  name = "generate-documents-background"

[[functions]]
  # Standard function for health checks
  path = "/.netlify/functions/health-check"
  name = "health-check"

[[functions]]
  # Scheduled function for cleanup
  path = "/.netlify/functions/cleanup-old-data"
  name = "cleanup-old-data"

# Configure Edge Functions
[[edge_functions]]
  path = "/api/edge/auth-check"
  function = "auth-check"

# Set timeout for Next.js API routes (max 10 seconds on free plan)
[[functions]]
  path = "/api/generate-resume"
  timeout = 10

[[functions]]
  path = "/api/generate-cover-letter"
  timeout = 10

[[functions]]
  path = "/api/resumeupload"
  timeout = 10

[[functions]]
  path = "/api/documents/parse"
  timeout = 10

[[functions]]
  path = "/api/jobs/match"
  timeout = 10

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# API CORS headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Optimize images
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  autoLaunch = false